# Basic numpy

In [1]:
import numpy as np

In [3]:
my_crappy_list = [1,2,3,4,5] + [1,3,5,7,9]
my_crappy_list

[1, 2, 3, 4, 5, 1, 3, 5, 7, 9]

In [4]:
my_awesome_array = np.array(my_crappy_list)
my_awesome_array

array([1, 2, 3, 4, 5, 1, 3, 5, 7, 9])

In [6]:
my_awesome_array[4], my_crappy_list[4]

(5, 5)

In [8]:
type(_6)

tuple

In [7]:
my_awesome_array.shape

(10,)

In [9]:
my_awesome_array.dtype

dtype('int64')

In [10]:
my_other_list = [1, 2, 3, 4, 5.5]
print(my_other_list)
my_other_array = np.array(my_other_list)
print(my_other_array)

[1, 2, 3, 4, 5.5]
[1.  2.  3.  4.  5.5]


In [11]:
my_other_array.dtype

dtype('float64')

In [12]:
my_other_array[0]

1.0

In [13]:
my_big_value_list = [100, 300, 500]
my_big_value_array = np.array(my_big_value_list, dtype='int8')
my_big_value_array

array([100,  44, -12], dtype=int8)

# Creating numpy arrays

In [14]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
print(list(range(50)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [18]:
zarr = np.zeros(50)
zarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
zarr.shape

(50,)

In [20]:
zarr2 = np.zeros((20, 15))
zarr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [21]:
zarr2.shape

(20, 15)

In [22]:
oarr = np.ones((5,7))
oarr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
zarr3 = np.zeros((2, 4, 5))
zarr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [24]:
np.linspace(-5, 5, 31)

array([-5.        , -4.66666667, -4.33333333, -4.        , -3.66666667,
       -3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ,
       -1.66666667, -1.33333333, -1.        , -0.66666667, -0.33333333,
        0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667,  2.        ,  2.33333333,  2.66666667,  3.        ,
        3.33333333,  3.66666667,  4.        ,  4.33333333,  4.66666667,
        5.        ])

In [25]:
np.random.rand(5, 10)

array([[0.27645016, 0.59699508, 0.75492752, 0.18052385, 0.98077467,
        0.2096481 , 0.00637405, 0.43949798, 0.23470387, 0.33819189],
       [0.71278441, 0.46648025, 0.34523099, 0.81226879, 0.70878731,
        0.94468647, 0.3803383 , 0.91216756, 0.66955086, 0.44149065],
       [0.30418217, 0.56967513, 0.45135891, 0.28427207, 0.93539023,
        0.81839862, 0.12717001, 0.63319563, 0.07325536, 0.41608673],
       [0.72602997, 0.60880631, 0.13070232, 0.42992416, 0.84959643,
        0.98375753, 0.8706854 , 0.35300373, 0.899799  , 0.04319786],
       [0.87283725, 0.37016502, 0.76975301, 0.00874729, 0.13332148,
        0.79480855, 0.92301512, 0.43062035, 0.20863335, 0.44993802]])

# Array arithmetic

In [26]:
print(my_awesome_array)
print(my_awesome_array + 1)

[1 2 3 4 5 1 3 5 7 9]
[ 2  3  4  5  6  2  4  6  8 10]


In [27]:
my_awesome_array - 1

array([0, 1, 2, 3, 4, 0, 2, 4, 6, 8])

In [28]:
my_awesome_array * 5.7

array([ 5.7, 11.4, 17.1, 22.8, 28.5,  5.7, 17.1, 28.5, 39.9, 51.3])

In [31]:
print(my_awesome_array / 2.0)
my_awesome_array / 2.0

[0.5 1.  1.5 2.  2.5 0.5 1.5 2.5 3.5 4.5]


array([0.5, 1. , 1.5, 2. , 2.5, 0.5, 1.5, 2.5, 3.5, 4.5])

In [30]:
my_awesome_array ** 2

array([ 1,  4,  9, 16, 25,  1,  9, 25, 49, 81])

In [33]:
np.zeros((2,3,4)) + 7

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]],

       [[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]])

# Arithmetic with multiple arrays

In [35]:
my_reversed_array = my_awesome_array[::-1]
my_reversed_array

array([9, 7, 5, 3, 1, 5, 4, 3, 2, 1])

In [37]:
my_awesome_array

array([1, 2, 3, 4, 5, 1, 3, 5, 7, 9])

In [36]:
my_awesome_array + my_reversed_array

array([10,  9,  8,  7,  6,  6,  7,  8,  9, 10])

In [42]:
[a + b for a,b in zip(my_awesome_array, my_reversed_array)]

[10, 9, 8, 7, 6, 6, 7, 8, 9, 10]

In [38]:
my_awesome_array - my_reversed_array

array([-8, -5, -2,  1,  4, -4, -1,  2,  5,  8])

In [39]:
my_awesome_array * my_reversed_array

array([ 9, 14, 15, 12,  5,  5, 12, 15, 14,  9])

In [40]:
my_awesome_array / my_reversed_array

array([0.11111111, 0.28571429, 0.6       , 1.33333333, 5.        ,
       0.2       , 0.75      , 1.66666667, 3.5       , 9.        ])

In [41]:
my_awesome_array ** my_reversed_array

array([  1, 128, 243,  64,   5,   1,  81, 125,  49,   9])

In [44]:
arr = np.zeros((2,3,4)) + 7
arr

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]],

       [[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]])

# Indexing into arrays

In [45]:
arr.shape

(2, 3, 4)

In [46]:
arr[0,1,3]

7.0

In [47]:
arr[0,1,3] = 8
arr

array([[[7., 7., 7., 7.],
        [7., 7., 7., 8.],
        [7., 7., 7., 7.]],

       [[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]])

In [50]:
biggerarr = np.zeros((40,3,4)) + 7

In [52]:
biggerarr[:10].shape

(10, 3, 4)

In [53]:
biggerarr[:10,:2,:3].shape

(10, 2, 3)

In [55]:
rarr = np.arange(70).reshape(2,7,5)
rarr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [56]:
rarr[:,2,:].shape

(2, 5)

In [57]:
rarr[:,2,:]

array([[10, 11, 12, 13, 14],
       [45, 46, 47, 48, 49]])