In [1]:
import numpy as np

# Boolean array indexing

In [2]:
arr = np.arange(4)

In [3]:
arr

array([0, 1, 2, 3])

In [4]:
inds = [True, False, False, True]
arr[inds]

array([0, 3])

In [5]:
bad_inds = [True, False, False, True, False]
arr[bad_inds]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 5

In [6]:
arr

array([0, 1, 2, 3])

In [7]:
arr > 1

array([False, False,  True,  True])

In [8]:
arr2 = np.array([1, 2, 0, 1])
arr2

array([1, 2, 0, 1])

In [9]:
arr2 > arr

array([ True,  True, False, False])

In [10]:
arr2_bad = np.array([1, 2, 0, 1, 3])
arr2_bad > arr

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [12]:
arr

array([0, 1, 2, 3])

In [13]:
arr > 1

array([False, False,  True,  True])

In [14]:
arr[arr > 1]

array([2, 3])

In [15]:
which_are_greater = arr > 1
arr[which_are_greater]

array([2, 3])

# Aggregation

In [16]:
test_arr = np.array([0.3, 1.7, 0.2, 0.1])
test_arr

array([0.3, 1.7, 0.2, 0.1])

In [17]:
test_arr.min

<function ndarray.min>

In [18]:
test_arr.min()

0.1

In [19]:
test_arr2 = np.array([0.3, 1.7, 0.2, 0.1, -2.5])
test_arr2.min()

-2.5

In [20]:
np.min(test_arr2)

-2.5

In [21]:
# can be combined with other things
arr[arr > 1].min() # smallest element of arr that's greater than 1

2

In [27]:
2, 2., 2.0

(2, 2.0, 2.0)

In [23]:
test_arr2

array([ 0.3,  1.7,  0.2,  0.1, -2.5])

In [24]:
test_arr2.sum() # the sum of the numbers

-0.19999999999999973

In [28]:
test_arr2.prod() # the product of the numbers

-0.025500000000000002

In [29]:
test_arr2.mean() # the mean of the numbers

-0.039999999999999945

In [30]:
test_arr2.std() # standard deviation

1.3617635624439361

In [31]:
test_arr2.var() # variance

1.8544

In [32]:
test_arr2.min() # minimum value

-2.5

In [33]:
test_arr2.max() # maximum value

1.7

In [34]:
test_arr2

array([ 0.3,  1.7,  0.2,  0.1, -2.5])

In [35]:
test_arr2.argmin() # arg min, index of the minimum value

4

In [37]:
test_arr2[test_arr2.argmin()]

-2.5

In [36]:
test_arr2.argmax() # the index of the maximum value

1

In [38]:
test_arr2.median() # not a method!

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [39]:
np.median(test_arr2) # the median value

0.2

In [40]:
barr = np.array([True, False, False, False])
barr2 = np.array([True, True, True, True])
barr3 = np.array([False, False, False, False])

In [41]:
# are any of the values True?
print(barr.any())
print(barr2.any())
print(barr3.any())

True
True
False


In [42]:
# are all of the values True?
print(barr.all())
print(barr2.all())
print(barr3.all())

False
True
False


# Aggregation over dimensions

In [44]:
twodarr = np.random.randint(0, 10, (4,6))
twodarr

array([[0, 5, 8, 7, 0, 5],
       [1, 3, 8, 0, 2, 3],
       [0, 7, 0, 1, 9, 7],
       [0, 4, 1, 4, 9, 1]])

In [45]:
twodarr.sum()

85

In [46]:
twodarr.shape

(4, 6)

In [47]:
[twodarr[:,col].sum() for col in range(twodarr.shape[1])]

[1, 19, 17, 12, 20, 16]

In [48]:
twodarr.sum(axis=0) # takes the sum ACROSS axis=0 (rows)

array([ 1, 19, 17, 12, 20, 16])

In [50]:
twodarr.sum(axis=0).shape

(6,)

In [49]:
twodarr.sum(axis=1) # takes the sum ACROSS axis=1 (columns)

array([25, 17, 24, 19])

In [51]:
twodarr.sum(axis=1).shape

(4,)

In [52]:
ndarr = np.ones((3, 5, 10, 50, 4))
ndarr.shape

(3, 5, 10, 50, 4)

In [54]:
ndarr.size

30000

In [56]:
ndarr.sum(axis=3).shape

(3, 5, 10, 4)