In [1]:
import numpy as np

# Assignment Recap

In [2]:
test = np.arange(10)
test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
test[3] = 33 # assigning a single value

In [4]:
test

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9])

In [5]:
test2 = np.arange(10)
test2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
test2[:5] = 33
test2

array([33, 33, 33, 33, 33,  5,  6,  7,  8,  9])

In [7]:
test3 = np.arange(10)
test3[::2] = 33
test3

array([33,  1, 33,  3, 33,  5, 33,  7, 33,  9])

In [9]:
test4 = np.arange(10)
test4[:3] = np.array([90, 80, 70])
test4

array([90, 80, 70,  3,  4,  5,  6,  7,  8,  9])

# Broadcasting

In [10]:
arr = np.arange(500).reshape((50,10))
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [12]:
to_add = np.arange(10)[::-1]
to_add

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
arr[0] # first row of our array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[0].shape, to_add.shape # same shape

((10,), (10,))

In [16]:
arr[0] + to_add # we can add to_add to one row, that works great

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [17]:
arr.shape

(50, 10)

## How do we add to_add to EVERY row of arr?

In [44]:
# we can do it using a for loop
# but this is messy and gross
arr_copy = arr.copy()
for i in range(arr_copy.shape[0]):
    arr_copy[i] = arr_copy[i] + to_add

arr_copy

array([[  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [ 19,  19,  19,  19,  19,  19,  19,  19,  19,  19],
       [ 29,  29,  29,  29,  29,  29,  29,  29,  29,  29],
       [ 39,  39,  39,  39,  39,  39,  39,  39,  39,  39],
       [ 49,  49,  49,  49,  49,  49,  49,  49,  49,  49],
       [ 59,  59,  59,  59,  59,  59,  59,  59,  59,  59],
       [ 69,  69,  69,  69,  69,  69,  69,  69,  69,  69],
       [ 79,  79,  79,  79,  79,  79,  79,  79,  79,  79],
       [ 89,  89,  89,  89,  89,  89,  89,  89,  89,  89],
       [ 99,  99,  99,  99,  99,  99,  99,  99,  99,  99],
       [109, 109, 109, 109, 109, 109, 109, 109, 109, 109],
       [119, 119, 119, 119, 119, 119, 119, 119, 119, 119],
       [129, 129, 129, 129, 129, 129, 129, 129, 129, 129],
       [139, 139, 139, 139, 139, 139, 139, 139, 139, 139],
       [149, 149, 149, 149, 149, 149, 149, 149, 149, 149],
       [159, 159, 159, 159, 159, 159, 159, 159, 159, 159],
       [169, 169, 169, 169, 169, 169, 169, 169, 169, 169

In [21]:
arr.shape, to_add.shape

((50, 10), (10,))

In [19]:
arr + to_add # broadcasting is magic!

array([[  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [ 19,  19,  19,  19,  19,  19,  19,  19,  19,  19],
       [ 29,  29,  29,  29,  29,  29,  29,  29,  29,  29],
       [ 39,  39,  39,  39,  39,  39,  39,  39,  39,  39],
       [ 49,  49,  49,  49,  49,  49,  49,  49,  49,  49],
       [ 59,  59,  59,  59,  59,  59,  59,  59,  59,  59],
       [ 69,  69,  69,  69,  69,  69,  69,  69,  69,  69],
       [ 79,  79,  79,  79,  79,  79,  79,  79,  79,  79],
       [ 89,  89,  89,  89,  89,  89,  89,  89,  89,  89],
       [ 99,  99,  99,  99,  99,  99,  99,  99,  99,  99],
       [109, 109, 109, 109, 109, 109, 109, 109, 109, 109],
       [119, 119, 119, 119, 119, 119, 119, 119, 119, 119],
       [129, 129, 129, 129, 129, 129, 129, 129, 129, 129],
       [139, 139, 139, 139, 139, 139, 139, 139, 139, 139],
       [149, 149, 149, 149, 149, 149, 149, 149, 149, 149],
       [159, 159, 159, 159, 159, 159, 159, 159, 159, 159],
       [169, 169, 169, 169, 169, 169, 169, 169, 169, 169

In [22]:
# what if we wanted to add a vector to each COLUMN of arr?
to_add2 = np.arange(50)
arr.shape, to_add2.shape

((50, 10), (50,))

In [23]:
arr + to_add2 # doesn't work!

ValueError: operands could not be broadcast together with shapes (50,10) (50,) 

### Broadcasting can apply to both arrays!

In [30]:
a = np.arange(3)
print(a.shape)
print(a)

(3,)
[0 1 2]


In [26]:
b = np.arange(3)[:,np.newaxis]
print(b.shape)
print(b)

(3, 1)
[[0]
 [1]
 [2]]


In [31]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [32]:
bb = np.arange(3)
bb.shape

(3,)

In [33]:
bb[:,np.newaxis].shape # np.newaxis "pads" with a length-1 dimension

(3, 1)

In [34]:
bb.reshape((3,1)).shape

(3, 1)

In [35]:
bb[np.newaxis,:].shape

(1, 3)

In [36]:
bb.reshape((1,3)).shape

(1, 3)

In [37]:
bb[:,np.newaxis] + bb

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [38]:
bb[:,np.newaxis] + bb[np.newaxis,:]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Why does some broadcasting work and some fail?

In [39]:
arr.shape, to_add.shape # why does this work?

((50, 10), (10,))

In [40]:
arr.shape, to_add2.shape # why does this NOT work?

((50, 10), (50,))

In [41]:
arr.shape, to_add2[np.newaxis].shape # why does this NOT work?

((50, 10), (1, 50))

In [42]:
# suppose we want to add to_add2 to each COLUMN of arr
# how?
arr.shape, to_add2[:,np.newaxis].shape

((50, 10), (50, 1))

In [43]:
arr + to_add2[:,np.newaxis] # this works!!

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141],
       [143, 144, 145, 146, 147, 148, 149, 150, 151, 152],
       [154, 155, 156, 157, 158, 159, 160, 161, 162, 163],
       [165, 166, 167, 168, 169, 170, 171, 172, 173, 174],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185