In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import numpy as np
import matplotlib.pyplot as plt

In [29]:
x = np.random.randn(10, 10)
y = np.random.randn(10)

beta, rank, res, sing = np.linalg.lstsq(x, y)
print(beta)

[-0.68429395  0.86917326  1.15680227  1.27638886  0.16450624 -0.27824189
  0.05053671 -0.43648166  1.29446392  0.77562254]


/Users/huth/anaconda3/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


In [30]:
rss = ((y - x.dot(beta))**2).sum()
print(rss)

5.372343061269307e-29


In [31]:
tss = (y ** 2).sum()
print(tss)

13.35645480637481


In [32]:
R2 = 1 - rss/tss
print(R2)

1.0


In [27]:
# fit using part of the data (here 70%)
x = np.random.randn(1000, 1000)
y = np.random.randn(1000)

beta, rank, res, sing = np.linalg.lstsq(x[:700], y[:700])
print(beta)

/Users/huth/anaconda3/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """


[ 7.40825686e-03  4.81362814e-02 -1.72512908e-02  1.59343703e-02
  6.47758439e-02  4.67042998e-03 -3.14996795e-03 -9.14113399e-02
 -8.82083917e-02 -3.35736134e-03  1.18093134e-02  2.97572456e-02
  4.56028410e-02  2.36826932e-03 -2.00459562e-02  6.08740705e-02
  1.52464780e-02  9.28101116e-02  1.72583093e-02 -2.99879862e-02
  3.22700486e-03  1.86970491e-02 -4.52080704e-02  2.21781254e-02
 -5.05765001e-02  1.70691637e-03 -7.11263424e-02 -2.28679698e-02
  5.27035213e-02  3.54966842e-02 -8.90757716e-02  3.17472017e-02
  6.28928505e-02 -3.14924789e-02 -2.11697026e-03 -2.29601538e-02
 -3.12034983e-02  9.17788420e-03  2.59557979e-03  1.53381912e-02
 -2.41972763e-02 -1.18604950e-01 -3.43322799e-02 -4.51144196e-04
 -8.72272406e-02 -3.64740063e-02  1.56545897e-02 -4.41083229e-02
  8.48622400e-02 -3.66068440e-02  9.83491484e-03 -3.13883817e-02
  5.18310789e-02 -1.02144770e-01 -2.86952288e-02  3.54273996e-02
 -9.84738733e-03  3.57721127e-03  2.79186852e-02  1.36323455e-02
 -8.06667108e-03  4.35022

In [28]:
# then test using the other data (here 30%)
# R^2 is not biased upwards! this is GOOD!
rss = ((y[700:] - x[700:].dot(beta))**2).sum()
tss = (y[700:] ** 2).sum()
R2_oos = 1 - rss/tss
print(R2_oos)

-2.173161793682687


# Regression Stability

In [35]:
# what happens if x1 and x2 are similar (but with no noise in y)?
x = np.vstack([[1, 1, 0, 1, 0], 
               [1, 0.99, 0, 1, 0]]).T

y = np.array([1, 1, 0, 1, 0])# + 0.01*np.random.randn(5)

beta, res, rank, sing = np.linalg.lstsq(x, y)
print(beta)

[ 1.0000000e+00 -5.7342821e-17]


/Users/huth/anaconda3/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [49]:
# what if x1 and x2 are VERY similar, and there is a little noise in y?
x = np.vstack([[1, 1, 0, 1, 0], 
               [1, 0.999, 0, 1, 0]]).T

y = np.array([1, 1, 0, 1, 0]) + 0.01*np.random.randn(5)
print(y)

beta, res, rank, sing = np.linalg.lstsq(x, y)
print(beta)
print(sing ** -1)

[ 0.99755967  1.00705518 -0.01178659  1.00251759  0.00164125]
[ 8.01659038 -7.01655175]
[4.08316326e-01 1.73176220e+03]


/Users/huth/anaconda3/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


In [ ]:
# many different values for (beta1, beta2) give almost the same answer!

In [44]:
x.dot([-22, 23])

array([1.   , 0.977, 0.   , 1.   , 0.   ])

In [45]:
x.dot([-2.27, 3.27])

array([1.     , 0.99673, 0.     , 1.     , 0.     ])

In [47]:
x.dot([15,-14])

array([1.   , 1.014, 0.   , 1.   , 0.   ])