In [1]:
import numpy as np

# Basic numpy ndarray indexing

In [2]:
arr = np.random.rand(100,20,30)

In [4]:
arr.shape

(100, 20, 30)

In [5]:
arr.ndim

3

In [6]:
arr[12,19,6]

0.6618783476325252

In [7]:
arr[12,19,5:8]

array([0.19808038, 0.66187835, 0.4703132 ])

In [8]:
arr[12,19,5:8].ndim

1

In [9]:
arr[5].shape

(20, 30)

In [10]:
arr[:5].shape

(5, 20, 30)

In [14]:
arr[:5,:,:].shape

(5, 20, 30)

In [12]:
arr[:,5].shape

(100, 30)

In [13]:
arr[:,:,5].shape

(100, 20)

# Advanced Indexing

In [15]:
lilarr = np.random.rand(10)*10
lilarr

array([8.6805573 , 1.57062351, 5.25522957, 5.53036587, 7.54422872,
       6.06079266, 5.18526481, 0.80080662, 7.80465003, 7.74338179])

In [16]:
indices_i_want = [2, 3, 6, 8]

In [17]:
lilarr[indices_i_want]

array([5.25522957, 5.53036587, 5.18526481, 7.80465003])

In [19]:
biggerarr = np.arange(10*5).reshape((10,5))
biggerarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [20]:
biggerarr.shape

(10, 5)

In [21]:
biggerarr[5,2]

27

In [22]:
biggerarr[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
biggerarr[[0,1,8,9]] # first two rows, last two rows

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [26]:
biggerarr[[0,1,8,9],:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [24]:
biggerarr[[0,1,8,9],4]

array([ 4,  9, 44, 49])

In [25]:
biggerarr[[1,0,9,8]]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [45, 46, 47, 48, 49],
       [40, 41, 42, 43, 44]])

## Indexing with Booleans

In [27]:
lilarr

array([8.6805573 , 1.57062351, 5.25522957, 5.53036587, 7.54422872,
       6.06079266, 5.18526481, 0.80080662, 7.80465003, 7.74338179])

In [28]:
boolarr = [True, True, False, False, False, 
           False, False, False, True, True]

In [29]:
len(boolarr), len(lilarr)

(10, 10)

In [30]:
lilarr[boolarr]

array([8.6805573 , 1.57062351, 7.80465003, 7.74338179])

In [31]:
biggerarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
biggerarr[boolarr]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# Array Comparisons

In [33]:
lilarr

array([8.6805573 , 1.57062351, 5.25522957, 5.53036587, 7.54422872,
       6.06079266, 5.18526481, 0.80080662, 7.80465003, 7.74338179])

In [34]:
lilarr > 6

array([ True, False, False, False,  True,  True, False, False,  True,
        True])

In [37]:
type(lilarr)

numpy.ndarray

In [35]:
biggerarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
biggerarr == 27

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [38]:
lilarr

array([8.6805573 , 1.57062351, 5.25522957, 5.53036587, 7.54422872,
       6.06079266, 5.18526481, 0.80080662, 7.80465003, 7.74338179])

In [39]:
another_lilarr = np.random.rand(10)*10
another_lilarr

array([0.63697403, 0.26361671, 3.60315447, 3.87525423, 6.38500413,
       1.83058262, 0.66749526, 7.39070329, 9.01551214, 5.61895038])

In [40]:
lilarr > another_lilarr

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True])

# fMRI Demo

In [42]:
# %load fmri_demo.py
import numpy as np

task = np.array([3,3,3,3,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,4,
                4,4,4,4,4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,1,1,1,
                1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,5,5,5,5,5,
                5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,6,6,6,6,6,6,6,6,6,6,3,3,3,3,3,3,3,
                3,3,3,1,1,1,1,1,1,1,1,1,1,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,
                6,4,4,4,4,4,4,4,4,4,4,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,2,
                2,2,2,2,2,2,2,2,2,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,3,3,3,
                3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,
                3,3,3,3,3,5,5,5,5,5,5,5,5,5,5,1,1,1,1,1,1,1,1,1,1,6,6,6,6,6,6,6,
                6,6,6,2,2,2,2,2,2,2,2,2,2])

data = np.load('example_fmri_data.npy')

In [44]:
task.shape

(300,)

In [45]:
data.shape

(300,)

In [49]:
task == 4

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [51]:
data[task==4]

array([-0.68273737, -0.4709759 , -0.9416872 , -1.26655025,  1.80850628,
       -0.23602322,  1.03732989, -2.44268584,  0.43806718, -1.44520354,
       -0.24258417, -2.15455951,  0.04881945,  1.73055434, -1.1002733 ,
        1.28728031, -0.76287996,  0.05902374, -1.2901212 , -0.28067699,
       -0.23291736, -0.60717151,  0.16491454,  1.20251232, -0.41810435,
        2.13444787,  1.12509325,  0.35610469, -0.14805427, -0.61682162,
        0.93204034,  0.94689026, -0.69843705,  0.3927338 , -0.28906653,
       -0.96368035, -2.18159606, -0.11886818, -2.66984675, -0.40351977,
        1.41142762, -0.77048685, -0.10438786, -0.72254237, -0.848369  ,
       -0.04630329, -1.01530176,  0.13045267, -0.06624907, -0.62219362])

In [53]:
data[task==2].mean()

1.0308123826529332

In [54]:
# compute difference in means
hand_mean = data[task==2].mean()
rest_mean = data[task==4].mean()

print(hand_mean - rest_mean)

1.2639059331826035
